using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DaggerfallConnect.Arena2;
using DaggerfallConnect.FallExe;
using Mirror;
using DaggerfallWorkshop.Game;
using DaggerfallWorkshop;
using DaggerfallWorkshop.Game.Items;
using DaggerfallWorkshop.Game.Entity;
using DaggerfallWorkshop.Game.Utility;
using DaggerfallWorkshop.Game.Questing;
using DaggerfallWorkshop.Game.MagicAndEffects;

public class LootCatcher : NetworkBehaviour
{
    public GameObject lootPrefab;
    public Transform[] locations;

    // Server authoritative state. These are static because every PlayerMultiplayer has a LootCatcher.
    static uint nextServerLootId = 1;
    static readonly Dictionary<uint, string> serverLootItemsById = new Dictionary<uint, string>();
    static readonly Dictionary<uint, int> serverLootVersionById = new Dictionary<uint, int>();

    // Local scene state. Also static so RPCs from any player's LootCatcher can find any local loot pile.
    static readonly Dictionary<uint, DaggerfallLoot> localLootById = new Dictionary<uint, DaggerfallLoot>();
    static readonly Dictionary<uint, string> localLootItemsById = new Dictionary<uint, string>();
    static readonly Dictionary<uint, int> localLootVersionById = new Dictionary<uint, int>();

    // Corpse loot uses the enemy NetworkIdentity.netId with a high-bit flag.
    // This keeps corpse loot IDs separate from dropped-loot IDs generated by nextServerLootId.
    const uint CorpseLootIdFlag = 0x80000000u;

    // Server corpse state can arrive before the local corpse marker exists on a client.
    // Store it here and apply it as soon as the local corpse registers.
    static readonly Dictionary<uint, string> pendingCorpseItemsById = new Dictionary<uint, string>();
    static readonly Dictionary<uint, int> pendingCorpseVersionById = new Dictionary<uint, int>();

    // Server-side timing gap: a client can kill/loot a network enemy while the listen-host
    // is paused in a popup/menu and has not yet produced/published its local corpse loot.
    // In that case the server receives a corpse loot update for a valid corpse lootId that
    // is not registered in serverLootItemsById yet. Do NOT reject+disable the client's loot
    // window; remember the client's remaining corpse contents and apply it when the server
    // corpse publish finally arrives.
    static readonly Dictionary<uint, string> serverPendingUnknownCorpseItemsById = new Dictionary<uint, string>();


    public static uint BuildCorpseLootId(uint enemyNetId)
    {
        return CorpseLootIdFlag | enemyNetId;
    }

    public static bool IsCorpseLootId(uint lootId)
    {
        return (lootId & CorpseLootIdFlag) != 0;
    }

    static bool TryGetCorpseLootIdFromEnemy(GameObject enemy, out uint corpseLootId)
    {
        corpseLootId = 0;

        if (enemy == null)
            return false;

        if (!NetworkClient.active && !NetworkServer.active)
            return false;

        NetworkIdentity networkIdentity = enemy.GetComponent<NetworkIdentity>();
        if (networkIdentity == null || networkIdentity.netId == 0)
            return false;

        corpseLootId = BuildCorpseLootId(networkIdentity.netId);
        return true;
    }

    static LootCatcher FindAnyUsableLootCatcher()
    {
        if (PlayerMultiplayer.localPlayer != null)
        {
            LootCatcher local = PlayerMultiplayer.localPlayer.GetComponent<LootCatcher>();
            if (local != null)
                return local;
        }

        LootCatcher[] catchers = FindObjectsOfType<LootCatcher>();
        for (int i = 0; i < catchers.Length; i++)
        {
            if (catchers[i] != null && catchers[i].isLocalPlayer)
                return catchers[i];
        }

        if (catchers != null && catchers.Length > 0)
            return catchers[0];

        return null;
    }

    // Called from GameObjectHelper as soon as the local corpse marker exists.
    // This only establishes the local corpse <-> corpseLootId mapping. The server will publish
    // authoritative contents later after the normal DFU death/loot flow has populated the corpse.
    public static void RegisterLocalCorpseLootFromEnemy(GameObject enemy, DaggerfallLoot corpseLoot)
    {
        uint corpseLootId;
        if (!TryGetCorpseLootIdFromEnemy(enemy, out corpseLootId))
            return;

        if (corpseLoot == null)
            return;

        LootCatcher catcher = FindAnyUsableLootCatcher();
        if (catcher == null)
        {
            Debug.LogWarning("[LootCatcher] Could not register local corpse loot because no LootCatcher exists. corpseLootId=" + corpseLootId);
            return;
        }

        string localItems = SerializeLootItems(corpseLoot);
        catcher.RegisterLocalCorpseLoot(corpseLootId, 0, corpseLoot, localItems, "local-corpse-created");
    }

    // Called from DaggerfallEntityBehaviour on the server after the normal DFU death event has
    // produced the corpse container. This publishes the authoritative initial corpse contents.
    public static void ServerPublishCorpseLootFromEnemy(GameObject enemy, DaggerfallLoot corpseLoot)
    {
        if (!NetworkServer.active)
            return;

        uint corpseLootId;
        if (!TryGetCorpseLootIdFromEnemy(enemy, out corpseLootId))
            return;

        if (corpseLoot == null)
            return;

        LootCatcher catcher = FindAnyUsableLootCatcher();
        if (catcher == null)
        {
            Debug.LogWarning("[LootCatcher] Could not publish corpse loot because no LootCatcher exists. corpseLootId=" + corpseLootId);
            return;
        }

        string authoritativeItems = SerializeLootItems(corpseLoot);
        catcher.ServerPublishCorpseLoot(corpseLootId, corpseLoot, authoritativeItems);
    }

    void Start()
    {
        if (isLocalPlayer)
            init();
    }

    void init()
    {
        PlayerEnterExit pEnterExit = GameManager.Instance.PlayerEnterExit;
        locations = new Transform[3];
        locations[0] = pEnterExit.ExteriorParent.transform;
        locations[1] = pEnterExit.InteriorParent.transform;
        locations[2] = pEnterExit.DungeonParent.transform;

        StartCoroutine(Check());
    }

    int getLocationEnabled()
    {
        if (locations == null)
            return 0;

        for (int i = 0; i < locations.Length; i++)
        {
            if (locations[i] != null && locations[i].gameObject.activeSelf)
                return i;
        }

        return 0;
    }

    IEnumerator Check()
    {
        while (true)
        {
            DaggerfallLoot loot = getPlayerLoot(getLocationEnabled());
            if (loot != null)
                prepareLootSending(loot);

            yield return new WaitForSeconds(3.6f);
        }
    }

    Transform getLocationLoot(int loc)
    {
        if (locations == null || loc < 0 || loc >= locations.Length || locations[loc] == null)
            return null;

        // Original layout:
        // Exterior/Dungeon loose loot parent = child 2
        // Interior loose loot parent = child 1
        int childIndex = (loc == 1) ? 1 : 2;

        if (locations[loc].childCount <= childIndex)
            return null;

        return locations[loc].GetChild(childIndex);
    }

    DaggerfallLoot getPlayerLoot(int loc)
    {
        Transform lootParent = getLocationLoot(loc);
        if (lootParent == null)
            return null;

        foreach (Transform t in lootParent)
        {
            if (t == null)
                continue;

            if (t.name == "DroppedLoot")
            {
                DaggerfallLoot loot = t.gameObject.GetComponent<DaggerfallLoot>();
                if (loot != null && loot.playerOwned)
                {
                    // Mark this local dropped loot as already processed.
                    t.name += "#";
                    t.gameObject.layer = 0;

                    LootMultiplayer lootMultiplayer = t.gameObject.GetComponent<LootMultiplayer>();
                    if (lootMultiplayer == null)
                        lootMultiplayer = t.gameObject.AddComponent<LootMultiplayer>();

                    lootMultiplayer.lootCatcher = this;
                    return loot;
                }
            }
        }

        return null;
    }

    void prepareLootSending(DaggerfallLoot loot)
    {
        if (loot == null || loot.Items == null)
            return;

        string items = SerializeLootItems(loot);
        Debug.Log("[LootCatcher] Sending dropped loot items: " + items);

        Vector3 pos = loot.transform.position;
        string parentName = loot.transform.parent != null ? loot.transform.parent.name : string.Empty;

        cmdSpawnLoot(pos.x, pos.y, pos.z, items, parentName);
    }

    public static string SerializeLootItems(DaggerfallLoot loot)
    {
        if (loot == null || loot.Items == null)
            return string.Empty;

        string items = string.Empty;

        foreach (DaggerfallUnityItem item in loot.Items.CloneAll())
        {
            if (item == null)
                continue;

            // Keep the original stable serializer for all normal loot:
            // group @ template @ material @ stackCount
            // Only quest-linked loot receives extra metadata after those 4 fields.
            // This avoids touching the working normal loot/version behaviour while
            // preserving quest book identity for corpse loot (message + quest link).
            items += (int)item.ItemGroup + "@" +
                     item.TemplateIndex + "@" +
                     item.NativeMaterialValue + "@" +
                     item.stackCount;

            if (item.IsQuestItem && item.QuestUID != 0 && item.QuestItemSymbol != null &&
                !string.IsNullOrEmpty(item.QuestItemSymbol.Name))
            {
                items += "@Q@" +
                         item.QuestUID + "@" +
                         EscapeLootField(item.QuestItemSymbol.Name) + "@" +
                         item.message + "@" +
                         item.value + "@" +
                         item.CurrentVariant;
            }

            // Preserve only the per-instance magic/artifact properties that the original
            // four-field loot format cannot represent. Do not serialize UID or other save
            // state, and do not change any loot/network/version behaviour.
            //
            // Active quest items deliberately stay on the existing Q path unchanged.
            if (!item.IsQuestItem && (item.IsEnchanted || item.IsArtifact))
                AppendMagicLootMetadata(ref items, item);

            items += "#";
        }

        return items;
    }

    static string EscapeLootField(string value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        return value.Replace("%", "%25").Replace("@", "%40").Replace("#", "%23");
    }

    static string UnescapeLootField(string value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        return value.Replace("%23", "#").Replace("%40", "@").Replace("%25", "%");
    }

    static bool TryReadQuestLootMetadata(string[] infos, out ulong questUid, out string questSymbol, out int message, out int value, out int variant)
    {
        questUid = 0;
        questSymbol = string.Empty;
        message = 0;
        value = 0;
        variant = 0;

        // Old entries only have 4 fields and still work exactly as before.
        if (infos == null || infos.Length < 10 || infos[4] != "Q")
            return false;

        if (!ulong.TryParse(infos[5], out questUid))
            questUid = 0;

        questSymbol = UnescapeLootField(infos[6]);

        int.TryParse(infos[7], out message);
        int.TryParse(infos[8], out value);
        int.TryParse(infos[9], out variant);

        return questUid != 0 && !string.IsNullOrEmpty(questSymbol);
    }

    // M2 format is intentionally compact and item-only:
    // artifactIndex, flags, shortName, current/max condition, value, enchantmentPoints,
    // dye, variant, last health-leech use, legacy enchantments, custom enchantments.
    // It contains no UID and no loot/network state.
    static void AppendMagicLootMetadata(ref string items, DaggerfallUnityItem item)
    {
        if (item == null)
            return;

        int artifactIndex = -1;
        if (item.IsArtifact && (item.ArtifactIndexBitfield & 1) != 0)
            artifactIndex = item.ArtifactIndexBitfield >> 1;

        DaggerfallEnchantment[] legacy = item.legacyMagic;
        CustomEnchantment[] custom = item.customMagic;
        int legacyCount = legacy != null ? legacy.Length : 0;
        int customCount = custom != null ? custom.Length : 0;

        items += "@M2@" +
                 artifactIndex + "@" +
                 item.flags + "@" +
                 EscapeLootField(item.shortName) + "@" +
                 item.currentCondition + "@" +
                 item.maxCondition + "@" +
                 item.value + "@" +
                 item.enchantmentPoints + "@" +
                 (int)item.dyeColor + "@" +
                 item.CurrentVariant + "@" +
                 item.timeHealthLeechLastUsed + "@" +
                 legacyCount;

        for (int i = 0; i < legacyCount; i++)
        {
            items += "@" +
                     (int)legacy[i].type + "@" +
                     legacy[i].param;
        }

        items += "@" + customCount;

        for (int i = 0; i < customCount; i++)
        {
            string effectKey = custom[i].EffectKey;
            string customParam = custom[i].CustomParam;

            items += "@" +
                     EscapeLootField(effectKey) + "@" +
                     EscapeLootField(customParam);
        }
    }

    static bool TryApplyMagicLootMetadata(string[] infos, DaggerfallUnityItem item)
    {
        if (infos == null || item == null)
            return false;

        int marker = -1;
        for (int i = 4; i < infos.Length; i++)
        {
            if (infos[i] == "M2")
            {
                marker = i;
                break;
            }
        }

        if (marker < 0)
            return false;

        try
        {
            int p = marker + 1;
            int artifactIndex;
            int flagsValue;
            int currentCondition;
            int maxCondition;
            int value;
            int enchantmentPoints;
            int dyeValue;
            int variant;
            uint timeHealthLeechLastUsed;
            int legacyCount;

            if (p >= infos.Length || !int.TryParse(infos[p++], out artifactIndex) ||
                p >= infos.Length || !int.TryParse(infos[p++], out flagsValue))
                return false;

            if (p >= infos.Length)
                return false;
            string shortName = UnescapeLootField(infos[p++]);

            if (p >= infos.Length || !int.TryParse(infos[p++], out currentCondition) ||
                p >= infos.Length || !int.TryParse(infos[p++], out maxCondition) ||
                p >= infos.Length || !int.TryParse(infos[p++], out value) ||
                p >= infos.Length || !int.TryParse(infos[p++], out enchantmentPoints) ||
                p >= infos.Length || !int.TryParse(infos[p++], out dyeValue) ||
                p >= infos.Length || !int.TryParse(infos[p++], out variant) ||
                p >= infos.Length || !uint.TryParse(infos[p++], out timeHealthLeechLastUsed) ||
                p >= infos.Length || !int.TryParse(infos[p++], out legacyCount))
                return false;

            if (legacyCount < 0 || legacyCount > 64)
                return false;

            DaggerfallEnchantment[] legacy = legacyCount > 0
                ? new DaggerfallEnchantment[legacyCount]
                : null;

            for (int i = 0; i < legacyCount; i++)
            {
                int typeValue;
                short paramValue;

                if (p >= infos.Length || !int.TryParse(infos[p++], out typeValue) ||
                    p >= infos.Length || !short.TryParse(infos[p++], out paramValue))
                    return false;

                legacy[i].type = (EnchantmentTypes)typeValue;
                legacy[i].param = paramValue;
            }

            int customCount;
            if (p >= infos.Length || !int.TryParse(infos[p++], out customCount))
                return false;

            if (customCount < 0 || customCount > 64)
                return false;

            CustomEnchantment[] custom = customCount > 0
                ? new CustomEnchantment[customCount]
                : null;

            for (int i = 0; i < customCount; i++)
            {
                if (p + 1 >= infos.Length)
                    return false;

                custom[i] = new CustomEnchantment()
                {
                    EffectKey = UnescapeLootField(infos[p++]),
                    CustomParam = UnescapeLootField(infos[p++]),
                };
            }

            // Artifacts are reconstructed by DFU's own artifact setup. This restores the
            // actual artifact identity, textures, material and built-in magical effects.
            if (artifactIndex >= 0)
                item.SetArtifact(ItemGroups.Artifacts, artifactIndex);

            // Restore the exact per-instance magic state from the dropped item.
            item.flags = (ushort)Mathf.Clamp(flagsValue, 0, ushort.MaxValue);
            item.shortName = shortName;
            item.currentCondition = currentCondition;
            item.maxCondition = maxCondition;
            item.value = value;
            item.enchantmentPoints = enchantmentPoints;
            item.dyeColor = (DyeColors)dyeValue;
            item.timeHealthLeechLastUsed = timeHealthLeechLastUsed;
            item.legacyMagic = legacy;
            item.customMagic = custom;

            if (variant >= 0 && variant < item.TotalVariants)
                item.CurrentVariant = variant;

            return true;
        }
        catch (Exception ex)
        {
            // If M2 metadata is malformed, leave the already-created normal base item alone.
            Debug.LogWarning("[LootCatcher] Failed to restore magic/artifact loot metadata. Using base item instead. " + ex.Message);
            return false;
        }
    }

    public static bool IsSerializedLootEmpty(string items)
    {
        return string.IsNullOrEmpty(items);
    }

    [Command]
    void cmdSpawnLoot(float x, float y, float z, string items, string parentName)
    {
        uint lootId = nextServerLootId++;
        int version = 0;

        serverLootItemsById[lootId] = items;
        serverLootVersionById[lootId] = version;

        Debug.Log("[LootCatcher] Server registered lootId=" + lootId + " version=" + version + " items=" + items);

        rpcSpawnLoot(lootId, version, x, y, z, items, parentName);
    }

    [ClientRpc]
    void rpcSpawnLoot(uint lootId, int version, float x, float y, float z, string items, string parentName)
    {
        try
        {
            Vector3 pos = new Vector3(x, y, z);

            // The sender already has the real local dropped loot. Do not spawn a duplicate.
            // Instead, assign the network lootId to that existing local DroppedLoot# object.
            if (isLocalPlayer)
            {
                DaggerfallLoot existing = FindExistingLocalDroppedLootNear(pos);
                if (existing != null)
                {
                    RegisterLocalLoot(lootId, version, existing, items);
                    Debug.Log("[LootCatcher] Registered existing local dropped loot id=" + lootId + " version=" + version);
                }
                else
                {
                    Debug.LogWarning("[LootCatcher] Could not find sender's existing dropped loot near " + pos + " for lootId=" + lootId);
                }

                return;
            }

            if (lootPrefab == null)
            {
                Debug.LogError("[LootCatcher] Cannot spawn multiplayer loot because lootPrefab is null.");
                return;
            }

            GameObject parent = !string.IsNullOrEmpty(parentName) ? GameObject.Find(parentName) : null;
            if (parent == null)
            {
                Debug.LogWarning("[LootCatcher] Could not find loot parent '" + parentName + "'. Multiplayer loot not spawned.");
                return;
            }

            GameObject lootHandler = Instantiate(lootPrefab, pos, Quaternion.identity);
            if (lootHandler == null)
            {
                Debug.LogError("[LootCatcher] Instantiate(lootPrefab) returned null.");
                return;
            }

            lootHandler.transform.parent = parent.transform;
            lootHandler.transform.position = pos;
            lootHandler.name = "MultiplayerLoot_" + lootId;

            // Use a DFU-valid dropped-loot icon. DaggerfallInventoryWindow.OnPop()
            // indexes DaggerfallLootDataTables.dropIconIdxs[dropIconArchive][dropIconTexture]
            // for playerOwned loot. If TextureArchive/TextureRecord do not match DFU's
            // drop icon table, closing the inventory can throw IndexOutOfRangeException.
            int iconArchive = DaggerfallLootDataTables.randomTreasureArchive;
            int iconRecord = GetSafeDropIconRecord();

            DaggerfallBillboard billboard = lootHandler.GetComponent<DaggerfallBillboard>();
            if (billboard != null)
            {
                billboard.SetMaterial(iconArchive, iconRecord);
                billboard.AlignToBase();
            }
            else
            {
                Debug.LogWarning("[LootCatcher] Spawned loot prefab has no DaggerfallBillboard.");
            }

            DaggerfallLoot loot = lootHandler.GetComponent<DaggerfallLoot>();
            if (loot == null)
                loot = lootHandler.AddComponent<DaggerfallLoot>();

            // Fully initialise the loot metadata expected by the inventory window and by
            // GameObjectHelper.RemoveLootContainer().
            loot.LoadID = DaggerfallUnity.NextUID;
            loot.ContainerType = LootContainerTypes.DroppedLoot;
            loot.ContainerImage = InventoryContainerImages.Chest;
            loot.TextureArchive = iconArchive;
            loot.TextureRecord = iconRecord;
            loot.customDrop = true;

            // This replicated barrel is not this client's own freshly dropped pile.
            // Keeping playerOwned=false avoids the DFU OnPop crash path.
            loot.playerOwned = false;
            loot.WorldContext = GameManager.Instance.PlayerEnterExit.WorldContext;

            loot.Items.Clear();
            int addedCount = AddSerializedItemsToLoot(loot, items);

            LootMultiplayer lootMultiplayer = lootHandler.GetComponent<LootMultiplayer>();
            if (lootMultiplayer == null)
                lootMultiplayer = lootHandler.AddComponent<LootMultiplayer>();

            RegisterLocalLoot(lootId, version, loot, items);

            Debug.Log("[LootCatcher] Spawned multiplayer lootId=" + lootId + " at " + lootHandler.transform.position + " with " + addedCount + " item(s). version=" + version);
        }
        catch (Exception ex)
        {
            // Mirror disconnects clients if an RPC handler throws.
            Debug.LogError("[LootCatcher] rpcSpawnLoot failed, but exception was caught to avoid Mirror disconnect. " + ex);
        }
    }

    DaggerfallLoot FindExistingLocalDroppedLootNear(Vector3 pos)
    {
        DaggerfallLoot[] allLoot = FindObjectsOfType<DaggerfallLoot>();
        DaggerfallLoot best = null;
        float bestDist = float.MaxValue;

        for (int i = 0; i < allLoot.Length; i++)
        {
            DaggerfallLoot loot = allLoot[i];
            if (loot == null)
                continue;

            // Sender's real local drop was renamed from DroppedLoot to DroppedLoot# by getPlayerLoot().
            if (loot.name != "DroppedLoot#" && !loot.name.StartsWith("DroppedLoot"))
                continue;

            LootMultiplayer existingMP = loot.GetComponent<LootMultiplayer>();
            if (existingMP != null && existingMP.lootId != 0)
                continue;

            float dist = Vector3.Distance(loot.transform.position, pos);
            if (dist < bestDist)
            {
                bestDist = dist;
                best = loot;
            }
        }

        // Dropped pile positions should be very close, but allow some margin for parent/local offsets.
        if (best != null && bestDist <= 2.0f)
            return best;

        return null;
    }

    int GetSafeDropIconRecord()
    {
        int[] iconRecords = DaggerfallLootDataTables.randomTreasureIconIndices;
        if (iconRecords != null && iconRecords.Length > 0)
        {
            // Preserve the old barrel/treasure look if record 0 is valid for this archive.
            for (int i = 0; i < iconRecords.Length; i++)
            {
                if (iconRecords[i] == 0)
                    return 0;
            }

            return iconRecords[0];
        }

        return 0;
    }

    LootCatcher GetLocalLootCatcher()
    {
        if (PlayerMultiplayer.localPlayer != null)
        {
            LootCatcher catcher = PlayerMultiplayer.localPlayer.GetComponent<LootCatcher>();
            if (catcher != null)
                return catcher;
        }

        LootCatcher[] catchers = FindObjectsOfType<LootCatcher>();
        for (int i = 0; i < catchers.Length; i++)
        {
            if (catchers[i] != null && catchers[i].isLocalPlayer)
                return catchers[i];
        }

        // Fallback: prevents LootMultiplayer.lootCatcher from staying null.
        return this;
    }

    void RegisterLocalLoot(uint lootId, int version, DaggerfallLoot loot, string serializedItems)
    {
        if (loot == null)
            return;

        localLootById[lootId] = loot;
        localLootItemsById[lootId] = serializedItems ?? string.Empty;
        localLootVersionById[lootId] = version;

        LootMultiplayer lootMultiplayer = loot.GetComponent<LootMultiplayer>();
        if (lootMultiplayer == null)
            lootMultiplayer = loot.gameObject.AddComponent<LootMultiplayer>();

        lootMultiplayer.lootCatcher = GetLocalLootCatcher();
        lootMultiplayer.ConfigureNetworkLoot(lootId, version, serializedItems ?? string.Empty);

        if (!loot.name.Contains(lootId.ToString()))
            loot.name = loot.name + "_NetLoot_" + lootId;
    }

    static DaggerfallLoot FindLocalLootById(uint lootId)
    {
        DaggerfallLoot loot;
        if (localLootById.TryGetValue(lootId, out loot) && loot != null)
            return loot;

        LootMultiplayer[] all = FindObjectsOfType<LootMultiplayer>();
        for (int i = 0; i < all.Length; i++)
        {
            if (all[i] != null && all[i].lootId == lootId)
            {
                DaggerfallLoot found = all[i].GetComponent<DaggerfallLoot>();
                if (found != null)
                {
                    localLootById[lootId] = found;
                    return found;
                }
            }
        }

        return null;
    }

    int AddSerializedItemsToLoot(DaggerfallLoot loot, string items)
    {
        if (loot == null || loot.Items == null || string.IsNullOrEmpty(items))
            return 0;

        int addedCount = 0;
        string[] itemEntries = items.Split('#');

        foreach (string entry in itemEntries)
        {
            if (string.IsNullOrEmpty(entry))
                continue;

            string[] infos = entry.Split('@');
            if (infos.Length < 4)
            {
                Debug.LogWarning("[LootCatcher] Skipping malformed item entry: " + entry);
                continue;
            }

            int groupInt;
            int templateIndex;
            int material;
            int stackCount;

            if (!int.TryParse(infos[0], out groupInt) ||
                !int.TryParse(infos[1], out templateIndex) ||
                !int.TryParse(infos[2], out material) ||
                !int.TryParse(infos[3], out stackCount))
            {
                Debug.LogWarning("[LootCatcher] Skipping unparsable item entry: " + entry);
                continue;
            }

            ItemGroups itemGroup = getItemGroup(groupInt);
            if (itemGroup == ItemGroups.None)
                continue;

            ulong questUid;
            string questSymbol;
            int questBookMessage;
            int questItemValue;
            int questVariant;
            bool hasQuestMetadata = TryReadQuestLootMetadata(infos, out questUid, out questSymbol, out questBookMessage, out questItemValue, out questVariant);

            DaggerfallUnityItem item = null;

            // Quest books are the important special case. A book is not uniquely described
            // by ItemGroup + TemplateIndex. The actual book identity is item.message.
            // Without this, quest books from corpses rebuild as unrelated random books.
            if (hasQuestMetadata && itemGroup == ItemGroups.Books && questBookMessage > 0)
                item = ItemBuilder.CreateBook(questBookMessage);

            if (item == null)
                item = ItemBuilder.CreateItem(itemGroup, templateIndex);

            if (item == null)
            {
                Debug.LogWarning("[LootCatcher] ItemBuilder returned null for group=" + itemGroup + " templateIndex=" + templateIndex);
                continue;
            }

            item.stackCount = Mathf.Max(1, stackCount);

            switch (itemGroup)
            {
                case ItemGroups.Weapons:
                    ItemBuilder.ApplyWeaponMaterial(item, (WeaponMaterialTypes)material);
                    break;

                case ItemGroups.Armor:
                    PlayerEntity pEntity = GameManager.Instance.PlayerEntity;
                    ItemBuilder.ApplyArmorSettings(item, pEntity.Gender, pEntity.Race, (ArmorMaterialTypes)material);
                    break;
            }

            // Optional M2 metadata only augments the item created by the original path.
            // It does not alter the loot update/RPC/version mechanism.
            TryApplyMagicLootMetadata(infos, item);

            if (hasQuestMetadata)
            {
                try
                {
                    item.LinkQuestItem(questUid, new Symbol(questSymbol));
                    if (questBookMessage > 0)
                        item.message = questBookMessage;
                    if (questItemValue > 0)
                        item.value = questItemValue;
                    if (questVariant >= 0 && questVariant < item.TotalVariants)
                        item.CurrentVariant = questVariant;
                }
                catch (Exception ex)
                {
                    Debug.LogWarning("[LootCatcher] Failed to restore quest loot metadata for symbol='" + questSymbol + "': " + ex.Message);
                }
            }

            loot.Items.AddItem(item);
            addedCount++;
        }

        return addedCount;
    }

    ItemGroups getItemGroup(int i)
    {
        switch ((ItemGroups)i)
        {
            case ItemGroups.QuestItems:
                return ItemGroups.None;
        }

        return (ItemGroups)i;
    }



    void RegisterLocalCorpseLoot(uint corpseLootId, int version, DaggerfallLoot corpseLoot, string serializedItems, string reason)
    {
        if (corpseLoot == null)
            return;

        RegisterLocalLoot(corpseLootId, version, corpseLoot, serializedItems ?? string.Empty);

        // When the corpse marker is first created, DFU may still be finishing the corpse
        // item population. Do not let LootMultiplayer send an "unknown corpse lootId" update
        // before the server publishes the authoritative initial state.
        LootMultiplayer corpseLootMultiplayer = corpseLoot.GetComponent<LootMultiplayer>();
        if (corpseLootMultiplayer != null && reason == "local-corpse-created")
            corpseLootMultiplayer.SuppressContentUpdatesFor(1.0f);

        if (!corpseLoot.name.Contains("CorpseNetLoot"))
            corpseLoot.name = corpseLoot.name + "_CorpseNetLoot_" + corpseLootId;

        string pendingItems;
        int pendingVersion;
        if (pendingCorpseItemsById.TryGetValue(corpseLootId, out pendingItems))
        {
            pendingCorpseVersionById.TryGetValue(corpseLootId, out pendingVersion);
            pendingCorpseItemsById.Remove(corpseLootId);
            pendingCorpseVersionById.Remove(corpseLootId);

            Debug.Log("[LootCatcher] Applying pending corpse loot state. corpseLootId=" + corpseLootId + " version=" + pendingVersion + " reason=" + reason);
            ApplyReplaceLootContents(corpseLootId, pendingVersion, pendingItems);
            return;
        }

        Debug.Log("[LootCatcher] Registered local corpse loot. corpseLootId=" + corpseLootId + " version=" + version + " reason=" + reason + " items=" + (serializedItems ?? string.Empty));
    }

    [Server]
    public void ServerPublishCorpseLoot(uint corpseLootId, DaggerfallLoot corpseLoot, string authoritativeItems)
    {
        if (!NetworkServer.active)
            return;

        const int version = 0;

        string pendingClientItems;
        if (serverPendingUnknownCorpseItemsById.TryGetValue(corpseLootId, out pendingClientItems))
        {
            serverPendingUnknownCorpseItemsById.Remove(corpseLootId);
            authoritativeItems = pendingClientItems ?? string.Empty;
            Debug.LogWarning("[LootCatcher] Applied pending client corpse loot update during delayed server publish. corpseLootId=" + corpseLootId + " items=" + authoritativeItems);
        }

        serverLootItemsById[corpseLootId] = authoritativeItems ?? string.Empty;
        serverLootVersionById[corpseLootId] = version;

        RegisterLocalCorpseLoot(corpseLootId, version, corpseLoot, authoritativeItems ?? string.Empty, "server-publish");

        Debug.Log("[LootCatcher] Server published corpse loot. corpseLootId=" + corpseLootId + " version=" + version + " items=" + (authoritativeItems ?? string.Empty));
        rpcRegisterCorpseLoot(corpseLootId, version, authoritativeItems ?? string.Empty);
    }

    [ClientRpc]
    void rpcRegisterCorpseLoot(uint corpseLootId, int version, string authoritativeItems)
    {
        try
        {
            DaggerfallLoot localCorpse = FindLocalLootById(corpseLootId);
            if (localCorpse != null)
            {
                ApplyReplaceLootContents(corpseLootId, version, authoritativeItems ?? string.Empty);
                return;
            }

            pendingCorpseItemsById[corpseLootId] = authoritativeItems ?? string.Empty;
            pendingCorpseVersionById[corpseLootId] = version;

            Debug.Log("[LootCatcher] Stored pending corpse loot state. corpseLootId=" + corpseLootId + " version=" + version);
        }
        catch (Exception ex)
        {
            Debug.LogError("[LootCatcher] rpcRegisterCorpseLoot failed for corpseLootId=" + corpseLootId + ". " + ex);
        }
    }

    bool IsInventoryCurrentlyViewingLoot(DaggerfallLoot loot)
    {
        try
        {
            if (loot == null || DaggerfallUI.Instance == null)
                return false;

            var inventoryWindow = DaggerfallUI.Instance.InventoryWindow;
            if (inventoryWindow == null)
                return false;

            if (inventoryWindow.LootTarget != loot)
                return false;

            if (DaggerfallUI.Instance.UserInterfaceManager != null &&
                DaggerfallUI.Instance.UserInterfaceManager.TopWindow != inventoryWindow)
                return false;

            return true;
        }
        catch (Exception ex)
        {
            Debug.LogWarning("[LootCatcher] IsInventoryCurrentlyViewingLoot failed: " + ex.Message);
            return false;
        }
    }

    void TryRefreshOpenLootWindow(DaggerfallLoot loot, string reason)
    {
        try
        {
            if (!IsInventoryCurrentlyViewingLoot(loot))
                return;

            var inventoryWindow = DaggerfallUI.Instance.InventoryWindow;
            if (inventoryWindow == null)
                return;

            inventoryWindow.Refresh();

            Debug.Log("[LootCatcher] Refreshed open loot window after network loot update. reason=" + reason);
        }
        catch (Exception ex)
        {
            Debug.LogWarning("[LootCatcher] TryRefreshOpenLootWindow failed: " + ex.Message);
        }
    }

    public void NotifyLootContentsChanged(uint lootId, int baseVersion, string newSerializedItems)
    {
        if (!isLocalPlayer)
        {
            LootCatcher local = GetLocalLootCatcher();
            if (local != null && local != this)
            {
                local.NotifyLootContentsChanged(lootId, baseVersion, newSerializedItems);
                return;
            }
        }

        if (!isLocalPlayer)
            return;

        Debug.Log("[LootCatcher] Sending content update lootId=" + lootId + " baseVersion=" + baseVersion + " items=" + newSerializedItems);
        cmdUpdateLootContents(lootId, baseVersion, newSerializedItems ?? string.Empty);
    }

    [Command]
    void cmdUpdateLootContents(uint lootId, int baseVersion, string newSerializedItems)
    {
        if (!serverLootItemsById.ContainsKey(lootId))
        {
            if (IsCorpseLootId(lootId))
            {
                // Valid corpse loot timing gap. The client has a local corpse and removed an item,
                // but the host/server has not created/published its corpse yet because host time/UI
                // is paused. Queue the client's remaining contents and ACK without replacing or
                // disabling the client's loot window. When ServerPublishCorpseLoot() runs later,
                // this pending state becomes the initial authoritative corpse state.
                serverPendingUnknownCorpseItemsById[lootId] = newSerializedItems ?? string.Empty;
                Debug.LogWarning("[LootCatcher] Queued update for unknown corpse lootId=" + lootId + " until server corpse publish. items=" + (newSerializedItems ?? string.Empty));
                TargetAcknowledgePendingUnknownCorpseUpdate(connectionToClient, lootId, baseVersion, newSerializedItems ?? string.Empty);
                return;
            }

            Debug.LogWarning("[LootCatcher] Server rejected content update for unknown lootId=" + lootId);
            TargetResyncLootContents(connectionToClient, lootId, 0, string.Empty, true);
            return;
        }

        int currentVersion = 0;
        serverLootVersionById.TryGetValue(lootId, out currentVersion);

        // Version guard. This prevents an older stale window-close update from overwriting
        // a newer server loot state. It does not fully prevent inventory duping if two players
        // loot the same item at the exact same time; that requires a real lock-on-open system.
        if (baseVersion != currentVersion)
        {
            string currentItems = serverLootItemsById[lootId];
            Debug.LogWarning("[LootCatcher] Server rejected stale loot update. lootId=" + lootId + " clientBase=" + baseVersion + " serverVersion=" + currentVersion);
            TargetResyncLootContents(connectionToClient, lootId, currentVersion, currentItems, false);
            return;
        }

        if (string.IsNullOrEmpty(newSerializedItems))
        {
            if (IsCorpseLootId(lootId))
            {
                int emptyCorpseVersion = currentVersion + 1;
                serverLootItemsById[lootId] = string.Empty;
                serverLootVersionById[lootId] = emptyCorpseVersion;

                Debug.Log("[LootCatcher] Server accepted empty corpse loot update. Keeping corpse marker active. lootId=" + lootId + " version=" + emptyCorpseVersion);
                rpcReplaceLootContents(lootId, emptyCorpseVersion, string.Empty);
                return;
            }

            serverLootItemsById.Remove(lootId);
            serverLootVersionById.Remove(lootId);
            Debug.Log("[LootCatcher] Server accepted empty loot update. Disabling lootId=" + lootId);
            rpcDisableLootById(lootId);
            return;
        }

        int newVersion = currentVersion + 1;
        serverLootItemsById[lootId] = newSerializedItems;
        serverLootVersionById[lootId] = newVersion;

        Debug.Log("[LootCatcher] Server accepted loot update. lootId=" + lootId + " version=" + newVersion + " items=" + newSerializedItems);
        rpcReplaceLootContents(lootId, newVersion, newSerializedItems);
    }

    [TargetRpc]
    void TargetResyncLootContents(NetworkConnection target, uint lootId, int version, string items, bool disable)
    {
        if (disable)
            ApplyDisableLootById(lootId);
        else
            ApplyReplaceLootContents(lootId, version, items);
    }

    [TargetRpc]
    void TargetAcknowledgePendingUnknownCorpseUpdate(NetworkConnection target, uint lootId, int version, string items)
    {
        try
        {
            DaggerfallLoot loot = FindLocalLootById(lootId);
            if (loot == null)
                return;

            localLootItemsById[lootId] = items ?? string.Empty;
            localLootVersionById[lootId] = version;

            LootMultiplayer lootMultiplayer = loot.GetComponent<LootMultiplayer>();
            if (lootMultiplayer != null)
                lootMultiplayer.ConfigureNetworkLoot(lootId, version, items ?? string.Empty);

            Debug.Log("[LootCatcher] ACK pending unknown corpse update. lootId=" + lootId + " version=" + version);
        }
        catch (Exception ex)
        {
            Debug.LogWarning("[LootCatcher] TargetAcknowledgePendingUnknownCorpseUpdate failed for lootId=" + lootId + ": " + ex.Message);
        }
    }

    [ClientRpc]
    void rpcReplaceLootContents(uint lootId, int version, string items)
    {
        ApplyReplaceLootContents(lootId, version, items);
    }

    void ApplyReplaceLootContents(uint lootId, int version, string items)
    {
        try
        {
            DaggerfallLoot loot = FindLocalLootById(lootId);
            if (loot == null)
            {
                Debug.LogWarning("[LootCatcher] Could not find local lootId=" + lootId + " to replace contents.");
                return;
            }

            LootMultiplayer lootMultiplayer = loot.GetComponent<LootMultiplayer>();
            if (lootMultiplayer != null)
                lootMultiplayer.BeginNetworkApply();

            loot.Items.Clear();
            int added = AddSerializedItemsToLoot(loot, items);

            localLootItemsById[lootId] = items ?? string.Empty;
            localLootVersionById[lootId] = version;

            if (lootMultiplayer != null)
            {
                lootMultiplayer.ConfigureNetworkLoot(lootId, version, items ?? string.Empty);
                lootMultiplayer.EndNetworkApply();
            }

            TryRefreshOpenLootWindow(loot, "replace-contents");

            Debug.Log("[LootCatcher] Applied content replacement for lootId=" + lootId + " version=" + version + " itemCount=" + added);
        }
        catch (Exception ex)
        {
            Debug.LogError("[LootCatcher] ApplyReplaceLootContents failed for lootId=" + lootId + ". " + ex);
        }
    }

    public void NotifyLootRemovedDelayed(uint lootId, Vector3 fallbackPos)
    {
        if (!isLocalPlayer)
        {
            LootCatcher local = GetLocalLootCatcher();
            if (local != null && local != this)
            {
                local.NotifyLootRemovedDelayed(lootId, fallbackPos);
                return;
            }
        }

        if (!isLocalPlayer)
            return;

        StartCoroutine(NotifyLootRemovedDelayedCoroutine(lootId, fallbackPos));
    }

    IEnumerator NotifyLootRemovedDelayedCoroutine(uint lootId, Vector3 fallbackPos)
    {
        // Do not send the network disable while DaggerfallInventoryWindow.OnPop() is still
        // cleaning up. Waiting one frame avoids re-entering inventory/loot cleanup logic.
        yield return null;

        if (lootId != 0)
            cmdDisableLootById(lootId);
        else
            DisableLootOn(fallbackPos);
    }

    [Command]
    void cmdDisableLootById(uint lootId)
    {
        serverLootItemsById.Remove(lootId);
        serverLootVersionById.Remove(lootId);

        // Corpse markers are local DFU corpse objects. Do not network-disable them just
        // because one client cleaned/unloaded one locally. Empty corpse contents are synced
        // through rpcReplaceLootContents(..., string.Empty) instead.
        if (IsCorpseLootId(lootId))
        {
            Debug.Log("[LootCatcher] Ignoring network disable for corpse lootId=" + lootId + ". Local corpse cleanup is left to DFU/culling.");
            return;
        }

        rpcDisableLootById(lootId);
    }

    [ClientRpc]
    void rpcDisableLootById(uint lootId)
    {
        ApplyDisableLootById(lootId);
    }

    void ApplyDisableLootById(uint lootId)
    {
        DaggerfallLoot loot = FindLocalLootById(lootId);
        if (loot == null)
        {
            localLootById.Remove(lootId);
            localLootItemsById.Remove(lootId);
            localLootVersionById.Remove(lootId);
            return;
        }

        LootMultiplayer lootMultiplayer = loot.GetComponent<LootMultiplayer>();
        if (lootMultiplayer != null)
            lootMultiplayer.SuppressRemovalNotification();

        localLootById.Remove(lootId);
        localLootItemsById.Remove(lootId);
        localLootVersionById.Remove(lootId);

        // If this player currently has the loot window open, do not disable the object
        // out from under DaggerfallInventoryWindow. Clear the contents and refresh the UI.
        // When the player closes the now-empty window, DFU's normal OnPop cleanup can remove it.
        if (IsInventoryCurrentlyViewingLoot(loot))
        {
            loot.Items.Clear();
            TryRefreshOpenLootWindow(loot, "disable-while-open");
            Debug.Log("[LootCatcher] LootId=" + lootId + " emptied while inventory window is open. Leaving object active until window closes.");
            return;
        }

        loot.gameObject.SetActive(false);
    }

    // Position fallback kept for old/unregistered loot.
    public void DisableLootOn(Vector3 pos)
    {
        clientDisableLootOn(pos.x, pos.y, pos.z);
    }

    [Client]
    void clientDisableLootOn(float x, float y, float z)
    {
        if (!isLocalPlayer)
            return;

        cmdDisableLootOn(x, y, z);
    }

    [Command]
    void cmdDisableLootOn(float x, float y, float z)
    {
        rpcDisableLootOn(x, y, z);
    }

    [ClientRpc]
    void rpcDisableLootOn(float x, float y, float z)
    {
        Debug.Log("[LootCatcher] Disable loot at " + new Vector3(x, y, z));

        Collider[] hitColliders = Physics.OverlapSphere(new Vector3(x, y, z), 0.25f);
        foreach (Collider hitCollider in hitColliders)
        {
            if (hitCollider == null)
                continue;

            DaggerfallLoot loot = hitCollider.gameObject.GetComponent<DaggerfallLoot>();
            if (loot != null)
            {
                LootMultiplayer lootMultiplayer = hitCollider.gameObject.GetComponent<LootMultiplayer>();
                if (lootMultiplayer != null)
                    lootMultiplayer.SuppressRemovalNotification();

                hitCollider.gameObject.SetActive(false);
            }
        }
    }
}
